### ISSUE TITLE
Page/Sidebar Layout

### ISSUE THREAD

**Issue by elizabethmcd** [Arcadia-Science/arcadia-computational-training#36]
When first coming to the site, it isn't immediately clear that the upcoming trainings/schedule are under the "Arcadia Users Group" page. I would propose to put the first two paragraphs on the current "Arcadia Users Group" page (describing the purpose) on the home page, and changing the name of this page to "Upcoming Trainings/Schedule" or just "Trainings".

**Comment by taylorreiter** [comment]
Would you be willing to put in a PR for this? I don't totally understand the suggestion but it seems like it would make things more clear!

**Comment by elizabethmcd** [comment]
yes I will do a PR for this!
